[package]
name = "pewpew"
version = "0.3.3"
edition = "2018"

[dependencies]
ansi_term = "0.11"
base64 = "0.10"
clap = "2"
crossbeam = "0.6"
csv = "1"
chrono = "0.4"
fnv = "1"
futures = "0.1"
handlebars = "1"
hdrhistogram = "6"
hyper = "0.12"
hyper-tls = "0.3"
itertools = "0.8"
jsonpath = "0.1"
native-tls = "0.2"
percent-encoding = "1"
pest = "2"
pest_derive = "2"
parking_lot = "0.7"
rand = "0.6"
regex = "1"
serde = "1"
serde_derive = "1"
serde_json = "1"
serde-tuple-vec-map = "0.2"
serde_yaml = "0.8"
tokio = "0.1"
tokio-threadpool = "0.1"
unicode-segmentation = "1"
url = "1"

[dev-dependencies]
tempfile = "3"

[profile.release]
panic = "abort"